---
version: "3"
services:
  linuxserver:
    image: gnasello/sc-py-env:2023-10-13
    container_name: sc-py-env
    security_opt:
      - seccomp:unconfined # for terminal to work
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- SUBFOLDER=/ #optional
      #- TITLE=linuxserver #optional
    ports:
      - 3000:3000
    #devices:
      #- /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional