version: '3'

services:
  sc-env:
    image: gnasello/sc-env:2023-05-01
    build: .
    ports:
      - $JLPORT:$JLPORT
    volumes:
      - $HOME_RESEARCHER:/home/researcher # change the path before ":" with the volume you want to mount
    working_dir: /home/researcher
    hostname: localhost
    environment:
       - JLPORT=${JLPORT}