---
version: "3"
services:
  sc-py:
    image: gnasello/sc-py-env:2024-05-15
    container_name: sc-py-env
    user: root
    environment:
    - NB_USER=researcher
    - NB_UID=1234
    - NB_GID=1234
    - CHOWN_HOME=yes
    - CHOWN_HOME_OPTS=-R
    - GRANT_SUDO=yes
    ports:
      - 8888:8888