name: base
channels:
 - conda-forge
 - bioconda
dependencies:
 - jupyterlab-variableinspector
 - louvain
 - umap-learn
 - scanpy
 - rpy2
 - anndata2ri
 - multicore-tsne
 - scvelo
 - opentsne
 - plotly
 - scirpy
 - squidpy
 - bash_kernel
 - ipykernel
 - pip
 - pip:
    - igraph
    - leidenalg
